name: Deploy with Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t california-housing-app .

      - name: Run Docker container
        run: docker run -d -p 5000:5000 california-housing-app